export const REDIS_CLIENT = "REDIS_CLIENT";

// Queue
export const INJESTION_QUEUE = "INJESTION_QUEUE";
export const WEBHOOK_QUEUE = "WEBHOOK_QUEUE";
export const LLM_QUEUE = "LLM_QUEUE";
export const EMAIL_QUEUE = "EMAIL_QUEUE";

// Redis Key
export const REDIS_ORG_APP_INTEGRATION_STATUS_KEY_PREFIX = "REDIS_ORG_APP_INTEGRATION_STATUS_KEY_PREFIX";